set_property PACKAGE_PIN Y18 [get_ports clk1]
set_property IOSTANDARD LVCMOS33 [get_ports clk1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports usr_led1]
set_property IOSTANDARD LVCMOS33 [get_ports usr_led2]
set_property DRIVE 16 [get_ports usr_led1]
set_property DRIVE 16 [get_ports usr_led2]
set_property PACKAGE_PIN AA20 [get_ports clk_en]
set_property PACKAGE_PIN AB21 [get_ports usr_led1]
set_property PACKAGE_PIN AB20 [get_ports usr_led2]


set_property BITSTREAM.CONFIG.CONFIGRATE 104 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.PERSIST NO [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]